function [sim_x, sim_y] = epica_sim(obj,Y,M,m)
%
% FUNCTION: epica_sim(obj,Y,M,m)
%
% PURPOSE: use simple Euler's method to simulate data based on 1D
% stochastic ODE model
%
% INPUT: 
% - obj: DataSet object for the data you want to use
% - Y: number of "years" (sectors) to divide data into
% - M: number of "months" (subsections) to divide "years" into
% - m: offset in "years" for autocorrelation of f
%
% OUTPUT: 
% - sim_x: x-values for the resulting simulated data
% - sim_y: y-values generated by the simulation
%
%%

    % get model parameters for simulation
    [a,N,f,~] = findanf_epica(obj,Y,M,m);
    
    % set up time interval and white noise for simulation loop
    delt = range(obj.X) / (Y*M);
    wx = randn(Y*M);

    
    % set initial value of simulation
    global mean_y;
    i = 1;
    sim_y(i) = obj.Y(1) - mean_y;
    
    % run Euler's Method simulation
    for j=1:Y
        for k=1:M
            sim_y(i+1) = sim_y(i) + a(k)*sim_y(i)*delt + N(k)*sqrt(delt)*wx(i) + f(j)*delt;
            i = i + 1;
        end
    end
    
    % create array of x-values to go with simulated y-values
    sim_x = ( linspace(1,length(sim_y)+1,length(sim_y)) - length(sim_y) ) * range(obj.X) / length(sim_y);
    

end

